name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Node dependencies
        run: pnpm install

      - name: Build Next.js App
        working-directory: ./apps/web
        run: pnpm build

      - name: Build Go Indexer
        working-directory: ./indexer
        run: go build -o indexer main.go
